services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Africa/Lagos
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=Gra9tPa$$ed%1!
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
